name: 'Deploy Checkly Checks'

on:
  push:
    branches:
      - main

{% raw %}
env:
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
{% endraw %}

jobs:
  deploy-checks:
    name: Deploy Checkly Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: bunx checkly test

      - name: Verify Checkly credentials
        run: |
          if [ -z "$CHECKLY_API_KEY" ] || [ -z "$CHECKLY_ACCOUNT_ID" ]; then
            echo "Error: Required Checkly credentials are missing"
            exit 1
          fi

      - name: Deploy updated checks to Checkly
        run: bunx checkly deploy --force
